-- =============================================================================
-- MODELED Schema Views (Staging Views - self-contained references)
-- =============================================================================

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_LOYALTY__CUSTOMER_LOYALTY
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.CUSTOMER_LOYALTY
),
RENAMED AS (
    SELECT
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        CITY,
        COUNTRY,
        POSTAL_CODE,
        PREFERRED_LANGUAGE,
        GENDER,
        FAVOURITE_BRAND,
        MARITAL_STATUS,
        CHILDREN_COUNT,
        SIGN_UP_DATE,
        BIRTHDAY_DATE,
        E_MAIL,
        PHONE_NUMBER,
        LAST_UPDATE_TS
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__COUNTRY
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.COUNTRY
),
RENAMED AS (
    SELECT
        COUNTRY_ID      AS COUNTRY_ID,
        COUNTRY         AS COUNTRY_NAME,
        ISO_CURRENCY    AS ISO_CURRENCY_ALPHA_CD,
        ISO_COUNTRY     AS ISO_COUNTRY_ALPHA_2_CD,
        CITY_ID         AS CITY_ID,
        CITY            AS CITY_NAME,
        CITY_POPULATION AS CITY_POPULATION
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__FRANCHISE
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.FRANCHISE
),
RENAMED AS (
    SELECT
        FRANCHISE_ID,
        FIRST_NAME,
        LAST_NAME,
        CITY,
        COUNTRY,
        E_MAIL,
        PHONE_NUMBER
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__LOCATION
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.LOCATION
),
RENAMED AS (
    SELECT
        LOCATION_ID,
        PLACEKEY,
        LOCATION AS LOCATION_NAME,
        CITY,
        REGION,
        ISO_COUNTRY_CODE,
        COUNTRY
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__MENU
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.MENU
),
RENAMED AS (
    SELECT
        MENU_ID,
        MENU_TYPE_ID,
        MENU_TYPE,
        TRUCK_BRAND_NAME,
        MENU_ITEM_ID,
        MENU_ITEM_NAME,
        ITEM_CATEGORY,
        ITEM_SUBCATEGORY,
        COST_OF_GOODS_USD,
        SALE_PRICE_USD,
        MENU_ITEM_HEALTH_METRICS_OBJ
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__ORDER_DETAIL
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.ORDER_DETAIL
),
RENAMED AS (
    SELECT
        ORDER_DETAIL_ID,
        ORDER_ID,
        MENU_ITEM_ID,
        DISCOUNT_ID,
        LINE_NUMBER,
        QUANTITY,
        UNIT_PRICE,
        PRICE,
        ORDER_ITEM_DISCOUNT_AMOUNT
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__ORDER_HEADER
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.ORDER_HEADER
),
RENAMED AS (
    SELECT
        ORDER_ID,
        TRUCK_ID,
        LOCATION_ID,
        CUSTOMER_ID,
        DISCOUNT_ID,
        SHIFT_ID,
        SHIFT_START_TIME,
        SHIFT_END_TIME,
        ORDER_CHANNEL,
        ORDER_TS,
        SERVED_TS,
        ORDER_CURRENCY,
        ORDER_AMOUNT,
        ORDER_TAX_AMOUNT,
        ORDER_DISCOUNT_AMOUNT,
        ORDER_TOTAL
    FROM SOURCE
)
SELECT * FROM RENAMED;

DEFINE VIEW DEV_DBT_DEMO_BACKUP.MODELED.STG_POS__TRUCK
AS
WITH SOURCE AS (
    SELECT * FROM DEV_DBT_DEMO_BACKUP.RAW.TRUCK
),
RENAMED AS (
    SELECT
        TRUCK_ID,
        MENU_TYPE_ID,
        PRIMARY_CITY,
        REGION,
        ISO_REGION,
        COUNTRY,
        ISO_COUNTRY_CODE,
        FRANCHISE_FLAG,
        YEAR,
        MAKE,
        MODEL,
        EV_FLAG,
        FRANCHISE_ID,
        TRUCK_OPENING_DATE,
        TRUCK_TYPE
    FROM SOURCE
)
SELECT * FROM RENAMED;
