-- =============================================================================
-- MODELED Schema Tables (Transient Fact Tables)
-- =============================================================================

DEFINE TRANSIENT TABLE DEV_DBT_DEMO_BACKUP.MODELED.F_ORDER (
    ORDER_KEY BINARY(16),
    ORDER_ID NUMBER(38,0),
    TRUCK_KEY BINARY(16),
    LOCATION_KEY BINARY(16),
    CUSTOMER_KEY BINARY(16),
    SHIFT_ID NUMBER(38,0),
    ORDER_CURRENCY VARCHAR(3),
    ORDER_TS TIMESTAMP_NTZ(9),
    SHIFT_START_TIME TIME(9),
    SHIFT_END_TIME TIME(9),
    ORDER_AMOUNT NUMBER(38,4),
    ORDER_TOTAL NUMBER(38,4)
);

DEFINE TRANSIENT TABLE DEV_DBT_DEMO_BACKUP.MODELED.F_ORDER_LINE (
    ORDER_LINE_KEY BINARY(16),
    ORDER_DETAIL_ID NUMBER(38,0),
    ORDER_KEY BINARY(16),
    MENU_ITEM_KEY BINARY(16),
    LINE_NUMBER NUMBER(38,0),
    QUANTITY NUMBER(5,0),
    LINE_AMOUNT NUMBER(38,4),
    UNIT_PRICE NUMBER(38,4)
);
