manifest_version: 2
type: DCM_PROJECT
default_target: 'DEV'

targets:
  DEV:
    account_identifier: SFSENORTHAMERICA-DGILLIS_AWS_USEAST1_V1
    project_name: 'UTIL.DCM_PROJECT_ARCHIVE.DBT_COCO_DEMO_DCM'
    project_owner: SYSADMIN

templating:
  defaults:
    db: 'DEV_DBT_DEMO'
